/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Data;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author diego
 */
public class interfaz2 extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form interfaz
     */
    
    // Se inicializa el objeto de clase temporizador 
    temporizador temporizador = new temporizador(0, 0, 0);
    /*
       Se inicializa el hilo de la clase de temporizador
    */
    Thread reloj = new Thread(temporizador);
    
    public interfaz2() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setBackground(Color.WHITE);
        ActualizarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bninicio = new javax.swing.JButton();
        bnpausar = new javax.swing.JButton();
        bncontinuar = new javax.swing.JButton();
        lblcontador = new javax.swing.JLabel();
        jProduccion = new javax.swing.JPanel();
        jProduccionContenedor = new javax.swing.JPanel();
        lblProduccion = new javax.swing.JLabel();
        JEmpaquetado = new javax.swing.JPanel();
        JEmpaquetadoContenedor = new javax.swing.JPanel();
        lblEmpaquetado = new javax.swing.JLabel();
        JSalida = new javax.swing.JPanel();
        JSalidaContenedor = new javax.swing.JPanel();
        lblSalida = new javax.swing.JLabel();
        JpanelInventario = new javax.swing.JPanel();
        jInventario = new javax.swing.JPanel();
        lblInventario = new javax.swing.JLabel();
        lienzo1 = new Data.lienzo2();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lienzo2 = new Data.lienzo2();
        lienzo3 = new Data.lienzo2();
        lienzo4 = new Data.lienzo2();
        lienzo5 = new Data.lienzo2();
        txtInicio = new javax.swing.JLabel();
        txtFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        bninicio.setText("Inicio");
        bninicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bninicioActionPerformed(evt);
            }
        });

        bnpausar.setText("Pausa");
        bnpausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnpausarActionPerformed(evt);
            }
        });

        bncontinuar.setText("Continuar");
        bncontinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bncontinuarActionPerformed(evt);
            }
        });

        lblcontador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblcontador.setText("00:00:00");

        jProduccion.setBackground(new java.awt.Color(153, 255, 102));
        jProduccion.setPreferredSize(new java.awt.Dimension(295, 161));

        jProduccionContenedor.setBackground(new java.awt.Color(153, 255, 102));

        javax.swing.GroupLayout jProduccionContenedorLayout = new javax.swing.GroupLayout(jProduccionContenedor);
        jProduccionContenedor.setLayout(jProduccionContenedorLayout);
        jProduccionContenedorLayout.setHorizontalGroup(
            jProduccionContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jProduccionContenedorLayout.setVerticalGroup(
            jProduccionContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        lblProduccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProduccion.setText("Produccion: ");

        javax.swing.GroupLayout jProduccionLayout = new javax.swing.GroupLayout(jProduccion);
        jProduccion.setLayout(jProduccionLayout);
        jProduccionLayout.setHorizontalGroup(
            jProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProduccionContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jProduccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProduccion)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jProduccionLayout.setVerticalGroup(
            jProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jProduccionLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(lblProduccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProduccionContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JEmpaquetado.setBackground(new java.awt.Color(255, 204, 255));
        JEmpaquetado.setPreferredSize(new java.awt.Dimension(295, 161));

        JEmpaquetadoContenedor.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout JEmpaquetadoContenedorLayout = new javax.swing.GroupLayout(JEmpaquetadoContenedor);
        JEmpaquetadoContenedor.setLayout(JEmpaquetadoContenedorLayout);
        JEmpaquetadoContenedorLayout.setHorizontalGroup(
            JEmpaquetadoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JEmpaquetadoContenedorLayout.setVerticalGroup(
            JEmpaquetadoContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );

        lblEmpaquetado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmpaquetado.setText("Empaquetado: ");

        javax.swing.GroupLayout JEmpaquetadoLayout = new javax.swing.GroupLayout(JEmpaquetado);
        JEmpaquetado.setLayout(JEmpaquetadoLayout);
        JEmpaquetadoLayout.setHorizontalGroup(
            JEmpaquetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JEmpaquetadoContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JEmpaquetadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmpaquetado)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        JEmpaquetadoLayout.setVerticalGroup(
            JEmpaquetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JEmpaquetadoLayout.createSequentialGroup()
                .addComponent(lblEmpaquetado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(JEmpaquetadoContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JSalida.setBackground(new java.awt.Color(255, 204, 204));
        JSalida.setPreferredSize(new java.awt.Dimension(295, 161));

        JSalidaContenedor.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout JSalidaContenedorLayout = new javax.swing.GroupLayout(JSalidaContenedor);
        JSalidaContenedor.setLayout(JSalidaContenedorLayout);
        JSalidaContenedorLayout.setHorizontalGroup(
            JSalidaContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JSalidaContenedorLayout.setVerticalGroup(
            JSalidaContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        lblSalida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSalida.setText("Salida: ");

        javax.swing.GroupLayout JSalidaLayout = new javax.swing.GroupLayout(JSalida);
        JSalida.setLayout(JSalidaLayout);
        JSalidaLayout.setHorizontalGroup(
            JSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSalidaContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JSalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSalida)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        JSalidaLayout.setVerticalGroup(
            JSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JSalidaLayout.createSequentialGroup()
                .addComponent(lblSalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(JSalidaContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JpanelInventario.setBackground(new java.awt.Color(102, 153, 255));
        JpanelInventario.setPreferredSize(new java.awt.Dimension(295, 161));

        jInventario.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jInventarioLayout = new javax.swing.GroupLayout(jInventario);
        jInventario.setLayout(jInventarioLayout);
        jInventarioLayout.setHorizontalGroup(
            jInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        jInventarioLayout.setVerticalGroup(
            jInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        lblInventario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInventario.setText("Inventario");

        javax.swing.GroupLayout JpanelInventarioLayout = new javax.swing.GroupLayout(JpanelInventario);
        JpanelInventario.setLayout(JpanelInventarioLayout);
        JpanelInventarioLayout.setHorizontalGroup(
            JpanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JpanelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInventario)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        JpanelInventarioLayout.setVerticalGroup(
            JpanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelInventarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("Regresar");

        jButton2.setText("Reporte");

        javax.swing.GroupLayout lienzo2Layout = new javax.swing.GroupLayout(lienzo2);
        lienzo2.setLayout(lienzo2Layout);
        lienzo2Layout.setHorizontalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        lienzo2Layout.setVerticalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lienzo3Layout = new javax.swing.GroupLayout(lienzo3);
        lienzo3.setLayout(lienzo3Layout);
        lienzo3Layout.setHorizontalGroup(
            lienzo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );
        lienzo3Layout.setVerticalGroup(
            lienzo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lienzo4Layout = new javax.swing.GroupLayout(lienzo4);
        lienzo4.setLayout(lienzo4Layout);
        lienzo4Layout.setHorizontalGroup(
            lienzo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        lienzo4Layout.setVerticalGroup(
            lienzo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lienzo5Layout = new javax.swing.GroupLayout(lienzo5);
        lienzo5.setLayout(lienzo5Layout);
        lienzo5Layout.setHorizontalGroup(
            lienzo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        lienzo5Layout.setVerticalGroup(
            lienzo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        txtInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInicio.setText("Inicio: 10");

        txtFinal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFinal.setText("Final: 10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblcontador, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280)
                        .addComponent(jButton2)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bninicio)
                                .addGap(83, 83, 83)
                                .addComponent(bnpausar)
                                .addGap(61, 61, 61)
                                .addComponent(bncontinuar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lienzo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lienzo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lienzo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JEmpaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lienzo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JpanelInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JEmpaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcontador)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(97, 97, 97)
                        .addComponent(lienzo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lienzo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lienzo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lienzo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JpanelInventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bninicio)
                    .addComponent(bnpausar)
                    .addComponent(bncontinuar))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bninicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bninicioActionPerformed
        
        bninicio.setEnabled(false);
        // Se ejecuta el lienzo donde se ejecutara la animacion
        /*lienzo1.setColor(Color.yellow);
        lienzo1.inicio(1);*/
        startMaterias();
        //AddMaterias(6);
        
        //AddMaterias(3);
        /*lienzo2.setColor(Color.yellow);
        lienzo2.inicio(2);
        
        lienzo3.setColor(Color.yellow);
        lienzo3.inicio(3);
        
        lienzo4.setColor(Color.yellow);
        lienzo4.inicio(4);
        
        lienzo5.setColor(Color.yellow);
        lienzo5.inicio(5);*/
        
        // Se agrega el cambio resibido en la clase Observable(temporizador)
        temporizador.addObserver(this);
        // Se ejecuta el hilo del temporizador
        reloj.start();
        
        
    }//GEN-LAST:event_bninicioActionPerformed
    
    /*public void AddMaterias(){
     jPanel4.setLayout(null); // Establece el layout manager de parentPanel como null
jInventario.setBounds(0, 0, jPanel4.getWidth(), jPanel4.getHeight()); // Establece el tamaño de jInventario para que ocupe todo el espacio de parentPanel
jPanel4.add(jInventario); // Agrega jInventario a parentPanel

CirclePanel circlePanel = new CirclePanel(10); // Crea un panel con radio de 50
circlePanel.setBounds(0, 0, jInventario.getWidth(), jInventario.getHeight()); // Establece el tamaño de circlePanel para que ocupe todo el espacio de jInventario
jInventario.add(circlePanel); 
        System.out.println("Creado");
    }*/
    
    /*public void AddMaterias() {
        jPanel4.setLayout(null); // Establece el layout manager de parentPanel como null
jInventario.setBounds(0, 0, jPanel4.getWidth(), jPanel4.getHeight()); // Establece el tamaño de jInventario para que ocupe todo el espacio de parentPanel
jPanel4.add(jInventario);
    int circleSize = 10; // Tamaño de cada círculo
    int spacing = 10; // Espacio entre círculos
    int maxPerRow = Math.floorDiv(jInventario.getWidth(), circleSize + spacing); // Número máximo de círculos por fila
    List <CirclePanel> circles = new ArrayList<>(); // Lista de círculos
    int x = 0; // Coordenada x inicial
    int y = 0; // Coordenada y inicial

    // Agrega los círculos a la lista y los dibuja en el panel
    for (int i = 0; i < 30; i++) { // 30 es el número de círculos a agregar
        CirclePanel circlePanel = new CirclePanel(circleSize);
        circlePanel.setLocation(x, y);
        circles.add(circlePanel);
        jInventario.add(circlePanel);

        // Mueve las coordenadas para dibujar el siguiente círculo
        x += circleSize + spacing;

        // Si ya se agregó el número máximo de círculos por fila, pasa a la siguiente fila
        if (i % maxPerRow == maxPerRow - 1) {
            x = 0;
            y += circleSize + spacing;
        }
    }
        System.out.println("Agregado");
}*/

public static void initMaterias(int n){
    
    
}

public void AddMaterias(int n, JPanel parentPanel, JPanel container, Color color) {
     container.removeAll();
     JPanel container2 = new JPanel();
     container2.setLayout(null);
     container2.setBounds(0, 22, parentPanel.getWidth(), parentPanel.getHeight());
     container2.setBackground(parentPanel.getBackground());
     parentPanel.add(container2);
     
     int circleWidth = 50;
     int circleHeight = 50;
     int maxCirclesPerRow = container2.getWidth() / circleWidth;

     int currentX = 0;
     int currentY = 10;
     int totalWidth = 0;

     for (int i = 0; i < n; i++) {
         CirclePanel circlePanel = new CirclePanel(15,50);
         circlePanel.setBounds(currentX, currentY, circleWidth, circleHeight);
         circlePanel.setColor(color);
         container2.add(circlePanel);
         
         currentX += circleWidth;
         totalWidth += circleWidth;

         if (totalWidth >= container2.getWidth() || i % maxCirclesPerRow == maxCirclesPerRow - 1) {
             currentX = 0;
             currentY += circleHeight;
             totalWidth = 0;
         }
     }
     container2.repaint();
     System.out.println("agregado");
}





    
    
    
    
    
    public void startMaterias(){
        Timer timer = new Timer(2000, new ActionListener() {
        
        //timepo de inicio a inventario
           int index = 0;

        public void actionPerformed(ActionEvent e) {
            // Llama a la función que deseas
        InicioAInventario();
            index++;
            if (index == 1) {
                ((Timer) e.getSource()).stop(); // Detiene el temporizador
            }
        }  
    });
    timer.start(); // Inicia el temporizador
        System.out.println("Primero");
    
    
    
    

    }
    
    public void ActualizarDatos(){
        lblEmpaquetado.setText("Empaquetado: "+SG.nEmpaquetado);
        lblProduccion.setText("Produccion: "+SG.nProduccion);
        lblInventario.setText("Inventario: "+SG.nInventario);
        lblSalida.setText("Salida: "+SG.nSalida);
        txtFinal.setText("Final: "+SG.nFinal);
        txtInicio.setText("Inicio: "+SG.nInicio);
    }
    
   public void InicioAInventario(){
    Timer timer = new Timer(4000, new ActionListener() {
        int index = 0;

        public void actionPerformed(ActionEvent e) {
            // Llama a la función que deseas
        lienzo1.setColor(Color.yellow);
        lienzo1.inicio(1);
        
            index++;
                if(index==1){
        InventarioAProduccion();
        }
            if (index == SG.nPelotas) {
                ((Timer) e.getSource()).stop(); // Detiene el temporizador
            }
        }
    });
    timer.start(); // Inicia el temporizador
        System.out.println("Continua");
    
    }
   
   public void InventarioAProduccion(){
    Timer timer = new Timer(SG.tiempoInventario, new ActionListener() {
        int index = 0;

        public void actionPerformed(ActionEvent e) {
            // Llama a la función que deseas
        lienzo2.setColor(Color.BLUE);
        lienzo2.inicio(2);
        
            index++;
            if(index==1){
        ProduccionAEmapaquetado();
        }
            if (index == SG.nPelotas) {
                ((Timer) e.getSource()).stop(); // Detiene el temporizador
            }
        }
    });
    timer.start(); // Inicia el temporizador
        System.out.println("Continua2");
    
    }
   
   public void ProduccionAEmapaquetado(){
    Timer timer = new Timer(SG.tiempoProduccion, new ActionListener() {
        int index = 0;

        public void actionPerformed(ActionEvent e) {
            // Llama a la función que deseas
        lienzo3.setColor(Color.GREEN);
        lienzo3.inicio(3);
        
            index++;
               if(index==1){
        EmpaquetadoASalida();
        }
            if (index == SG.nPelotas) {
                ((Timer) e.getSource()).stop(); // Detiene el temporizador
            }
        }
    });
    timer.start(); // Inicia el temporizador
        System.out.println("Continua2");
    
    }
   
   public void EmpaquetadoASalida(){
    Timer timer = new Timer(SG.tiempoEmpaquetado, new ActionListener() {
        int index = 0;

        public void actionPerformed(ActionEvent e) {
            // Llama a la función que deseas
        lienzo4.setColor(Color.PINK);
        lienzo4.inicio(4);
        
            index++;
            if(index==1){
        SalidaAFinal();
        }
            if (index == SG.nPelotas) {
                ((Timer) e.getSource()).stop(); // Detiene el temporizador
            }
        }
    });
    timer.start(); // Inicia el temporizador
        System.out.println("Empaquetado");
    
    }
    
   public void SalidaAFinal(){
    Timer timer = new Timer(SG.tiempoSalida, new ActionListener() {
        int index = 0;

        public void actionPerformed(ActionEvent e) {
            // Llama a la función que deseas
        lienzo5.setColor(Color.PINK);
        lienzo5.inicio(5);
            index++;
            if (index == SG.nPelotas) {
                ((Timer) e.getSource()).stop(); // Detiene el temporizador
            }
        }
    });
    timer.start(); // Inicia el temporizador
        System.out.println("Empaquetado");
    
    }
   
    public static void MostrarMessage(){
        System.out.println("Holaaa");
    }
    
    
    
    
    private void bnpausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnpausarActionPerformed
        
        // Se pausea los hilos 
        lienzo1.pausar();
        reloj.suspend();
    }//GEN-LAST:event_bnpausarActionPerformed

    private void bncontinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bncontinuarActionPerformed
        
        // Se continua el hilo que se termino
        lienzo1.continuar();
        reloj.resume();
    }//GEN-LAST:event_bncontinuarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JEmpaquetado;
    private javax.swing.JPanel JEmpaquetadoContenedor;
    private javax.swing.JPanel JSalida;
    private javax.swing.JPanel JSalidaContenedor;
    private javax.swing.JPanel JpanelInventario;
    private javax.swing.JButton bncontinuar;
    private javax.swing.JButton bninicio;
    private javax.swing.JButton bnpausar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jInventario;
    private javax.swing.JPanel jProduccion;
    private javax.swing.JPanel jProduccionContenedor;
    private javax.swing.JLabel lblEmpaquetado;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblProduccion;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel lblcontador;
    private Data.lienzo2 lienzo1;
    private Data.lienzo2 lienzo2;
    private Data.lienzo2 lienzo3;
    private Data.lienzo2 lienzo4;
    private Data.lienzo2 lienzo5;
    private javax.swing.JLabel txtFinal;
    private javax.swing.JLabel txtInicio;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        /*
        Se agrega el texto actualizado en el label del contador
        el arg es el objeto tiempo que se recibe de la clase Observable(temporizador)
        
        */
        lblcontador.setText((String) arg);
    }

    public JPanel getJpanelInventario() {
        return JpanelInventario;
    }
    
    public JPanel getJInventario() {
        return jInventario;
    }
    
    public JPanel getJpanelProduccion() {
        return jProduccion;
    }
    
    public JPanel getJProdunccionContenedor() {
        return jProduccionContenedor;
    }
    
    public JPanel getJpanelEmpaquetado() {
        return JEmpaquetado;
    }
    
    public JPanel getJEmpaquetadoContenedor() {
        return JEmpaquetadoContenedor;
    }
    
    public JPanel getJSalida() {
        return JSalida;
    }
    
    public JPanel getJSalidaContenendor() {
        return JSalidaContenedor;
    }
}
